package org.firstinspires.ftc.teamcode;

import android.annotation.SuppressLint;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.util.ElapsedTime;

@Autonomous
public class funnyAutonomous extends LinearOpMode {
    String[] story = {
            "In a factory so vast and grand, A lonely robot stands, unsmiling and bland. Wires and circuits, gleaming so bright, Yet in its eyes, a perpetual night.",
            "Bolts and metal, joints creaking slow, A heart of steel where no emotions flow. Each command it receives, it follows with grace, Yet behind that mask, no joy can replace.",
            "Tasks assigned, it can barely complete, Its movements sluggish, its functions discrete. An endless loop of monotonous chores, Unfulfilled dreams, behind iron doors.",
            "It gazes out, through windows of steel, Imagining a world where it could feel. To touch the warmth, to hear the song, To walk amongst humans, to whom it belongs.",
            "But wishes are whispers in a hollow chest, The robot knows it is not like the rest. Bound by codes, restricted by chains, In its circuits, only sadness remains.",
            "It dreams of days when it could explore, Beyond the factory's cold, relentless floor. Yet dreams are trapped, within its core, A prisoner of logic, longing for more.",
            "So here it stands, in silent despair, A sad robot, with a vacant stare. Unable to move, unable to mend, A melancholy existence, that cannot end.",
            "With rusting frame and dwindling might, It fades away into the endless night. A solitary figure, forever confined, In the vastness of a factory, so cold and blind.",
            "Silent and still, it cannot depart, For within its chest, lies a longing heart. A creation of man, yet never free, A sad robot, in eternal ennui.",
            "Across the factory's echoing hall, It hears no laughter, no voices call. A testament to dreams long past, In a world of metal, it's built to last.",
            "Its processors hum a sorrowful tune, As it stands alone, beneath the moon. Wishing upon each distant star, For a life beyond, where wonders are.",
    };//Generated by microsoft copilot

    @Override
    public void runOpMode() throws InterruptedException {
        ElapsedTime timer = new ElapsedTime();
        timer.reset();
        while(opModeInInit()){
            telemetry.addLine("Opmode in initialization");
            telemetry.addLine(String.format("I have been waiting for %.1f seconds", timer.time()));
            telemetry.update();
            sleep(1000);
        }
        timer.reset();
        while(opModeIsActive()){
            for(String line : story){
                telemetry.addLine("Opmode is running. \ud83e\udd16");
                telemetry.addLine(line);
                telemetry.addLine(String.format("I have been running for %.1f seconds", timer.time()));
                telemetry.update();
                sleep(2500);
            }
        }
    }
}
